services:
  traefik:
    image: docker.io/traefik:v3.2
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
    command: --providers.docker
    

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: banking_project
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # Mount code for local development (remove in prod)
      - .:/app
    restart: unless-stopped
    command: uvicorn src.backend.app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - postgres
      - mailpit
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.banking-project.entrypoints=web"
      - "traefik.http.routers.banking-project.rule=Host(`banking-project.localhost`)"
      - "traefik.http.routers.banking-project.service=banking-project"
      - "traefik.http.services.banking-project.loadbalancer.server.port=8000"
      - "traefik.http.services.banking-project.loadbalancer.server.scheme=http"
    
  mailpit:
    image: docker.io/axllent/mailpit:v1.20.3
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - banking_mailpit_data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  postgres:
    image: postgres:16-bullseye
    container_name: banking_postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  banking_mailpit_data:

