services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: banking_project
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # Mount code for local development (remove in prod)
      - .:/app
    restart: unless-stopped
    command: uvicorn src.backend.app.main:app --host 0.0.0.0 --port 8000
